package web1.web1.domain;

import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;


public enum DevSelectTime {
    ELEVENOCLOCK, ELEVENTEN, ELEVENTWENTY, ELEVENTHIRTY, ELEVENFOURTY, ELEVENFIFTY,
    TWELVEOCLOCK, TWELVETEN, TWELVETWENTY, TWELVETHIRTY, TWELVEFOURTY, TWELVEFIFTY,
    THIRTEENOCLOCK, THIRTEENTEN, THIRTEENTWENTY, THIRTEENTHIRTY, THIRTEENFOURTY, THIRTEENFIFTY,
    FOURTEENOCLOCK, FOURTEENTEN, FOURTEENTWENTY, FOURTEENTHIRTY, FOURTEENFOURTY, FOURTEENFIFTY,
    FIFTEENOCLOCK, FIFTEENTEN, FIFTEENTWENTY, FIFTEENTHIRTY, FIFTEENFOURTY, FIFTEENFIFTY

}
